<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="sfdc.tests.Login" tests="5" time="46.521" ignored="2" failures="1" timestamp="20 Nov 2021 22:13:46 GMT" skipped="0" hostname="DESKTOP-4FV91I7" errors="0">
  <testcase name="loginTC02" time="15.395" classname="sfdc.tests.Login"/>
  <testcase name="loginTC03" time="5.963" classname="sfdc.tests.Login">
    <failure type="java.lang.AssertionError" message="expected [] but found [sana@teckarch.com]">
      <![CDATA[java.lang.AssertionError: expected [] but found [sana@teckarch.com]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at sfdc.tests.Login.loginTC03(Login.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- loginTC03 -->
  <testcase name="loginTC01" time="7.697" classname="sfdc.tests.Login"/>
  <testcase name="loginTC04a" time="1.074" classname="sfdc.tests.Login"/>
  <testcase name="loginTC04b" time="16.392" classname="sfdc.tests.Login"/>
  <testcase name="TC07" classname="sfdc.tests.Home">
    <skipped/>
  </testcase> <!-- TC07 -->
  <testcase name="createoptyTC19" classname="sfdc.tests.CreateOpty">
    <skipped/>
  </testcase> <!-- createoptyTC19 -->
</testsuite> <!-- sfdc.tests.Login -->
